### ISSUE TITLE
restructure tool directory for easier onboarding

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#231]
```[tasklist]
### Tasks
- [x] restructure dirs
- [ ] modify get tools function in the install.sh script
- [ ] use the name of the tool in the config as ground source of truth -> configure lazy tool finder
- [ ] define how deep to search for lazy tool search
- [ ] change auto-upgrader to pull latest tools
- [ ] author/name:version - naming convention for configs: i.e. labdao/colabfold:standard@[hash of the commit]
- [ ] change the docs to avoid lazy tool finder (let's mention it, but not recommend using it)
```
