### ISSUE TITLE
update the PLEX README to be more descriptive

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#262]
```[tasklist]
### Tasks
- [ ] update base README 
- [ ] check the tests linked in the badges
- [ ] add a link once the "how to contribute section" is live
- [ ] add an ASCICinema to the PLEX in one minute section
```
