### ISSUE TITLE
replace typeform with airtable sign-up

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#304]
```[tasklist]
### Tasks
- [x] Create new AirTable form link
- [x] Ensure integration between form and AirTable DB
- [ ] Update typeform links in docs to AirTable
- [ ] Update install script exit logs to AirTable link
- [ ] Update Plex auto-message to AirTable link when `PLEX_ACCESS_TOKEN` not detected in env or not valid access token
```

**Comment by acashmoney** [comment]
Form link: https://airtable.com/shrfEDQj2fPffUge8

**Comment by mithrauki** [comment]
Airtable:

https://airtable.com/shrfEDQj2fPffUge8

Where it needs swapping: Install PLEX guide

https://docs.labdao.xyz/getting-started/install-plex

- In the intro, under "requirements" it says "get an access token here"
- In step 4: Add an access token. (it says "get an access token here" in the first para of this section)

**Comment by acashmoney** [comment]
Merged #326
