### ISSUE TITLE
nft.go helper functions

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#330]
```[tasklist]
### Tasks
- [x] build base token metadata
- [x] pin token metadata to ipfs and return cid
- [x] plex mint command
```

Details here: https://www.notion.so/labdao/NFT-Printer-Goes-Brr-24af2ef40e084a5796bb06779687a2ba
