### ISSUE TITLE
nft.go -> minting token

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#331]
```[tasklist]
### Tasks
- [x] address to send token to
- [x] config env variable to reduce spammed contract calls
- [x] delegated call to OZ Defender relayer
- [ ] geth integration
```

**Comment by acashmoney** [comment]
This ticket is being modified per new discussion around batteries not included vs batteries included. See https://www.notion.so/labdao/Web3-UI-52899d57a153476fb25178fd76f01c0e for more details

- [ ] web3 wallet integration with geth
- [ ] user pays gas fees to call contract
- [ ] auto message for option to upgrade to JupyterHub for gas-free minting
