### ISSUE TITLE
ProofOfScience v2 contract

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#350]
```[tasklist]
### Tasks
- [x] No longer an OZ `Ownable` contract so users can call the minting function
- [x] `CantBeEvil` CBE Exclusive license
- [x] Deploy contract
- [x] Verify contract on block explorer
- [ ] Add contract address to plex `MintNFT` function (see #331)
```
