### ISSUE TITLE
batteries not included NFT minting

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#364]
PR #362 adds batteries included (gas-less without connecting a wallet) NFT minting. Now we need to build batteries not included

```[tasklist]
### Tasks
- [ ] Connect to Alchemy endpoint
- [ ] Config file for pointing to chain and contract (optional)
- [ ] Update install script to grab config (optional)
- [ ] Call NFT contract
- [ ] Helpful logging
- [ ] Some link that users can visit to see their NFT
```
