### ISSUE TITLE
create a colabfold notebook

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#366]
```[tasklist]
### Tasks
- [x] Create a Colabfold notebook
- [x] Call Colabfold functions
- [x] Call MintNFT functions on Colabfold outputs
- [x] Confirm NFTs are minted
- [ ] integrate into python sdk
```
