### ISSUE TITLE
cids first - prototype io creation

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#390]
```[tasklist]
### Tasks
- [x] new CLI function for creating _intial_ `io.json`
- [x] matched files pinned to IPFS in their _own_ directory
- [x] directory CIDs written into inputs.ipfs
- [x] base name also written (no file path)
- [ ] modify tool struct to track CID
- [ ] add tool CID to initial `io.json`
- [x] upload `io.json` to IPFS and return CID
```

**Comment by acashmoney** [comment]
Closed with https://github.com/labdao/plex/pull/394
