### ISSUE TITLE
colabfold-nft reference notebook

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#392]
This notebook is intended to be a public-facing demonstration of running Colabfold on a Jupyter notebook. Users may also mint an NFT in a gas-less manner if they provide the needed webhook endpoint

```[tasklist]
### Tasks
- [x] Add notebook to public repo
- [ ] Modify AirTable form to include webhook
- [ ] Deploy notebook to tljh with ansible
```
